apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-sample-svc2
  annotations:
      image.openshift.io/triggers: >-
        [{"from":{"kind":"ImageStreamTag","name":"golang-sample-svc2:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"golang-sample-svc2\")].image"}]
  labels:
    app: golang-sample-svc2
    app.kubernetes.io/component: golang-sample-svc2
    app.kubernetes.io/instance: golang-sample-svc2
    app.kubernetes.io/name: golang-sample-svc2
    app.kubernetes.io/part-of: golang-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-sample-svc2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: golang-sample-svc2
        deploymentconfig: golang-sample-svc2
        version: default
    spec:
      containers:
        - name: golang-sample-svc2
          env:
            - name: SERVICE3_URL
              value: 'http://golang-sample-svc3:8080'
            - name: RESPONSE
              value: Red Hat OpenShift
            - name: SERVICE1_URL
              value: 'http://golang-sample-svc1:8080'
            - name: SERVICE2_URL
              value: 'http://golang-sample-svc2:8080'
            - name: JAEGER_SERVICE_NAME
              value: golang-sample-main.a-goex
            - name: JAEGER_PROPAGATION
              value: 'jaeger,b3,w3c'
            - name: JAEGER_ENDPOINT
              value: 'http://jaeger-collector.istio-system.svc:14268/api/traces'
            - name: OTELCOL_SERVER
              value: 'http://my-otelcol-collector:4317'
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: 'http://my-otelcol-collector:4318'
          image: image-registry.openshift-image-registry.svc:5000/a-goex/golang-sample-svc2
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
