apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: golang-sample-svc2
    app.kubernetes.io/component: golang-sample-svc2
    app.kubernetes.io/instance: golang-sample-svc2
    app.kubernetes.io/name: golang-sample-svc2
    app.kubernetes.io/part-of: golang-sample
  name: golang-sample-svc2
spec:
  lookupPolicy:
    local: false